### ISSUE TITLE
How to add an client to director?

### ISSUE THREAD

**Issue by e-it** [netmanagers/puppet-bacula#37]
Hello,

I'm using this module to deploy bacula to a backup-system and different clients.

Now I'm having some trouble on adding a new client to the director. The `clients.d`-directory is empty and there are no `jobs` or `filesets` defined.

How can I add them?

This is the YAML of my bacula-director-server:

```
  bacula:
    client_template: bacula/director/client.conf.erb
    console_template: bacula/bconsole.conf.erb
    default_messages: Daemon
    director_template: bacula/bacula-dir.conf.erb
    manage_client: 'false'
    manage_console: 'true'
    manage_director: 'true'
    manage_storage: 'true'
    source_dir_purge: 'true'
    storage_template: bacula/bacula-sd.conf.erb

```

This is the YAML of my bacula-client-server:

```
  bacula:
    client_template: bacula/director/client.conf.erb
    console_template: bacula/bconsole.conf.erb
    default_messages: Daemon
    director_template: bacula/bacula-dir.conf.erb
    manage_client: 'true'
    manage_console: 'false'
    manage_director: 'false'
    manage_storage: 'false'
    source_dir_purge: 'false'
    storage_template: bacula/bacula-sd.conf.erb

```
